mini_twitter_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mtweet import urls
from django.conf.urls.static import static
from django.conf import settings
from registration.backends.simple.views import RegistrationView
import notifications.urls



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mtweet.urls')),
    url(r'^account/', include('registration.backends.simple.urls')),
    url(r'^friendship/', include('friendship.urls')),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mtweet/urls.py
from django.conf.urls import url
from mtweet import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<username>[\w\-]+)/add_profile', views.add_profile, name="add_profile"),
    url(r'^home_page', views.home_page, name='home_page'),
    url(r'^add_post', views.add_post, name='add_post'),
    url(r'^add_comment', views.add_comment, name='add_comment'),
    url(r'^show_post/(?P<pid>[\w\-]+)', views.show_post, name="show_post"),
    url(r'^like_post', views.like_post, name='like_post'),
    url(r'^show_user', views.show_user, name="show_user"),
    url(r'^profile/(?P<username>[\w\-]+)', views.profile, name='profile'),
    url(r'^add_follower', views.add_follower, name="add_follower"),
    url(r'^like_count', views.like_count, name="like_count"),
    url(r'^in_search', views.in_search, name='in_search')
]

mtweet/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.

class UserProfile(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    user = models.OneToOneField(User)
    firstname = models.CharField(max_length=128)
    lastname = models.CharField(max_length=128)
    hometown = models.CharField(blank=True, max_length=128)
    display_picture = models.ImageField(blank=True)
    mobile = models.IntegerField(blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    follows = models.ManyToManyField('self', related_name='follower', symmetrical=False, blank=True)

    def __str__(self):
        return self.firstname


class Post(models.Model):
    user = models.ForeignKey(User)
    content = models.CharField(max_length=140, blank=False, help_text="Post")
    likes = models.IntegerField(default=0)
    post_time = models.DateTimeField(auto_now_add=True)
    comments = models.IntegerField(default=0)

    def __str__(self):
        return self.content

class Comment(models.Model):
    post = models.ForeignKey(Post)
    comment = models.CharField(max_length=128, blank=False, help_text='Comment')
    poster = models.CharField(blank=False, max_length=128)
    comment_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.poster

class Like(models.Model):
    user = models.ForeignKey(User)
    post = models.ForeignKey(Post)
    created = models.DateTimeField(auto_now_add=True)

mtweet/forms.py
from django import forms
from mtweet.models import UserProfile, Post, Comment
from django.contrib.auth.models import User

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('firstname','lastname','gender','hometown','display_picture', 'mobile')


class PostForm(forms.ModelForm):
    likes = forms.IntegerField(widget=forms.HiddenInput, initial=0)
    content = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Post
        fields = ('content', )


class CommentForm(forms.ModelForm):
    comment = forms.CharField()

    class Meta:
        model = Comment
        fields = ('comment', )

mtweet/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from mtweet.forms import PostForm, CommentForm, UserProfileForm
from mtweet.models import UserProfile, Post, Comment, Like
from django.contrib.auth.models import User
from friendship.models import Friend, Follow
from django.http import HttpResponse
import json
from django.core import serializers
from django.db.models.signals import post_save
from notifications.signals import notify


def my_handler(sender, instance, created, **kwargs):
    notify.send(instance, recipient=Post.user, verb='was saved')

def index(request):
	return render(request, 'mtweet/index.html')

@login_required
def home_page(request):
	user = request.user
	post_form = PostForm()
	post_list =[]
	profile = UserProfile.objects.get(user=user)
	all_following = Follow.objects.following(user)
	for following in all_following:
		post_list += Post.objects.filter(user=following).order_by('-post_time')
	def insertionSort(alist):
	   for index in range(1,len(alist)):
	    currentvalue = alist[index].post_time
	    currentuser = alist[index]
	    position = index
	    while position>0 and alist[position-1].post_time<currentvalue:
	        alist[position]=alist[position-1]
	        position = position-1
	    alist[position]=currentuser
	insertionSort(post_list)
	unread = user.notifications.unread()
	
	context_dict = {'post_form':post_form, 'post_list':post_list, 'unread':unread, 'profile':profile}
	return render(request, 'homepage/home_page.html', context_dict)

@login_required
def profile(request, username):
	user = request.user
	pro_user = User.objects.get(username=username)
	profile = UserProfile.objects.get(user=user)
	pro_profile = UserProfile.objects.get(user=pro_user)
	post_list_user = Post.objects.filter(user=user).order_by('-post_time')
	post_list_pro = Post.objects.filter(user=pro_user).order_by("-post_time")
	context_dict = {'user':user, 'profile':profile, 'pro_user':pro_user, 'pro_profile':pro_profile, 
					'post_list_user':post_list_user, 'post_list_pro':post_list_pro}
	return render(request, 'homepage/profile.html', context_dict)

@login_required
def show_user(request):
	user_list = User.objects.all().order_by('username')
	profile = UserProfile.objects.get(user=request.user)
	context_dict = {'user_list':user_list, 'profile':profile}
	return render(request, 'homepage/show_user.html', context_dict)

def add_profile(request, username):
	user = request.user
	if request.method == 'POST':
		profileform = UserProfileForm(request.POST)
		if profileform.is_valid():
			profile = profileform.save(commit=False)
			profile.user = user
			profile.save()
		return redirect(home_page)
	else:
		profileform = UserProfileForm()
	return render(request, 'mtweet/add_profile.html', {'profileform':profileform})

@login_required
def add_post(request):
	user = request.user
	if request.method == 'POST':
		content = request.POST['content']
		Post.objects.create(
				user=user,
				content=content,
			)

		return HttpResponse('')
	else:
		return home_page(request)

@login_required
def show_post(request, pid):
	comment_form = CommentForm()
	comment_list = None
	try:
		post = Post.objects.get(id=pid)
	except Post.DoesNotExist:
		post = None
	if post:
		comment_list = Comment.objects.filter(post=post).order_by('-comment_time')
		context_dict = {'post':post, 'comment_form':comment_form, 'comment_list':comment_list}
		return render(request, 'homepage/show_post.html', context_dict)
	else:
		return HttpResponse("No such post")

@login_required
def add_comment(request):
	if request.method == 'POST':
		comment = request.POST['comment']
		pid = request.POST['pid']
		post = Post.objects.get(id=pid)
		if post:
			Comment.objects.create(
					post=post,
					comment=comment,
					poster=request.user.username
				)
			post.comments += 1
			post.save()
			data = {}
			data['comment'] = comment
			data['user'] = request.user.username
			return HttpResponse(json.dumps(data), content_type='application/json')
		else:
			return HttpResponse("No such post")

@login_required
def like_post(request):
	if request.method == "GET":
		pid = request.GET['pid']
		post = Post.objects.get(id=pid)
		if post:
			new_like, created = Like.objects.get_or_create(user=request.user, post_id=pid)
			if not created:
				new_like.delete()
				liked = False
			else:
				liked = True
			count = Like.objects.filter(post=post).count()
			data = {'count':count, 'liked':liked}
			return HttpResponse(json.dumps(data), content_type='application/json')


@login_required
def add_follower(request):
	if request.method == "GET":
		username = request.GET['username']
		follow_user = User.objects.get(username=username)
		Follow.objects.add_follower(request.user, follow_user)
		return HttpResponse('')


def like_count(request):
	if request.method == "GET":
		pid = request.GET['pid']
		post = get_object_or_404(Post, id=pid)
		liked = Like.objects.filter(user=request.user, post=post)
		if liked:
			liked_this = True
		else:
			liked_this = False
		count = Like.objects.filter(post=post).count()
		data = {}
		data['count'] = count
		data['liked_this'] = liked_this
		return HttpResponse(json.dumps(data), content_type='application/json')

def in_search(request):
	if request.method == 'GET':
		usr_lst = []
		search = request.GET['search']
		if search == '':
			return HttpResponse('')
		serial = serializers.serialize('json', User.objects.filter(username__istartswith=search), fields=('username'))
		return HttpResponse(serial, content_type='application/json')
		

templates/mtweet/add_profile.html
{% extends 'mtweet/base.html' %}
{% load staticfiles %}
{% block title_block %}Add Profile{% endblock %}

{% block head_block %}
  <style media="screen">
    body {
      background: black!important;
    }
    .jumbotron {
      background-color: inherit;
    }
    .container {
      max-width: 600px;
    }
  </style>
{% endblock %}
{% block body_block %}
<link href="http://v4-alpha.getbootstrap.com/examples/signin/signin.css" rel="stylesheet">

<div class="jumbotron">
  <h1>Complete your profile</h1>
</div>
<div class="container">
  <form action="/{{ user.username }}/add_profile" method="post" enctype='multipart/form-data' >
    {% csrf_token %}
    <p>
      <input id="id_display_picture" name="display_picture" type="file">
    </p>
    <p class="required">
      <input id="id_firstname" maxlength="128" name="firstname" type="text" placeholder="First Name" required autofocus class="form-control">
    </p>
    <p class="required">
      <input id="id_lastname" maxlength="128" name="lastname" type="text" placeholder="Last Name" required class="form-control">
    </p>
    <p>
      <select id="id_gender" name="gender">
        <option value="" selected="selected">Gender</option>
        <option value="M">Male</option>
        <option value="F">Female</option>
      </select>
    </p>
    <p>
      <input id="id_mobile" name="mobile" type="number" placeholder="Mobile Number">
    </p>
    <input type="submit" value="Submit" class="btn btn-lg btn-primary">
  </form>
</div>
{% endblock %}

templates/mtweet/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="mayank kushal">
    <link rel="shortcut icon" href="{% static 'assets/ico/favicon.png'%}">

  <title>{% block title_block %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'assets/css/bootstrap.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'assets/css/main.css'%}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css'%}">

    <script src="{% static 'assets/js/jquery.min.js'%}"></script>
	<script src="{% static 'assets/js/modernizr.custom.js'%}"></script>



    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>
    {% block head_block %}{% endblock %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="assets/js/html5shiv.js"></script>
      <script src="assets/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body data-spy="scroll" data-offset="0" data-target="#theMenu">

	<!-- Menu -->
	<nav class="menu" id="theMenu">
		<div class="menu-wrap">
			<h1 class="logo"><a href="{% url 'index' %}">Mini Twitter</a></h1>
			<i class="icon-remove menu-close"></i>
      {% if user.is_authenticated %}
      <a href="{% url 'auth_logout' %}?next={% url 'index' %}" class="smoothScroll">Logout</a>
      {% else %}
			<a href="{% url 'auth_login' %}" class="smoothScroll">Login</a>
			<a href="{% url 'registration_register' %}" class="smoothScroll">Register</a>
      {% endif %}
		</div>

		<!-- Menu button -->
		<div id="menuToggle"><i class="icon-reorder"></i></div>
	</nav>



		{% block body_block %}{% endblock %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
	<script src="{% static 'assets/js/classie.js'%}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'assets/js/smoothscroll.js'%}"></script>
	<script src="{%static 'assets/js/main.js'%}"></script>
</body>
</html>

templates/mtweet/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="mayank kushal">
    <link rel="shortcut icon" href="{% static 'assets/ico/favicon.png'%}">

    <title>MINIMAL - Free Bootstrap 3 Theme</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'assets/css/bootstrap.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'assets/css/main.css'%}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css'%}">

    <script src="{% static 'assets/js/jquery.min.js'%}"></script>
	<script src="{% static 'assets/js/modernizr.custom.js'%}"></script>



    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="assets/js/html5shiv.js"></script>
      <script src="assets/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body data-spy="scroll" data-offset="0" data-target="#theMenu">
<style media="screen">
  .bttn {
    margin: 10px;
  }
</style>


	<!-- Menu -->
	<nav class="menu" id="theMenu">
		<div class="menu-wrap">
			<h1 class="logo"><a href="{% url 'index' %}">Mini Twitter</a></h1>
			<i class="icon-remove menu-close"></i>
      {% if user.is_authenticated %}
      <a href="{% url 'auth_logout' %}?next={% url 'index' %}" class="smoothScroll">Logout</a>
      {% else %}
      <a href="{% url 'auth_login' %}" class="smoothScroll">Login</a>
      <a href="{% url 'registration_register' %}" class="smoothScroll">Register</a>
      {% endif %}
		</div>

		<!-- Menu button -->
		<div id="menuToggle"><i class="icon-reorder"></i></div>
	</nav>



	<!-- ========== HEADER SECTION ========== -->
	<section id="home" name="home"></section>
	<div id="headerwrap">
		<div class="container">
			<div class="logo">
				<img src="assets/img/logo.png">
			</div>
			<br>
			<div class="row">
				<h1>MINI TWITTER</h1>
				<br>
				<h3>Hello, I'm almost Twitter</h3>
        {% if user.is_authenticated %}
          <a href="{% url 'auth_logout' %}?next={% url 'index' %}" class="btn btn-danger btn-lg bttn">Logout</a><a href="{% url 'home_page' %}" class="btn btn-lg btn-info">Dashboard</a>
        {% else %}
          <a href="{% url 'auth_login' %}" class="btn btn-info btn-lg">Login</a><a href="{% url 'registration_register' %}" class="btn btn-default btn-lg">SignUp</a>
        {% endif %}
				<br>
				<br>
				<div class="col-lg-6 col-lg-offset-3">
				</div>
			</div>
		</div><!-- /container -->
	</div><!-- /headerwrap -->



	<!-- ========== CAROUSEL SECTION ========== -->
	<section id="portfolio" name="portfolio"></section>
	<div id="f">
		<div class="container">
			<div class="row centered">
				<h3>SOME PROJECTS</h3>
				<p class="centered"><i class="icon icon-circle"></i><i class="icon icon-circle"></i><i class="icon icon-circle"></i></p>

				<div class="col-lg-6 col-lg-offset-3">
					<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
						<!-- Wrapper for slides -->
						<div class="carousel-inner">
							<div class="item active centered">
								<img class="img-responsive" src="assets/img/c1.png" alt="">
							</div>
							<div class="item centered">
								<img class="img-responsive" src="assets/img/c2.png" alt="">
							</div>
							<div class="item centered">
								<img class="img-responsive" src="assets/img/c3.png" alt="">
							</div>
						</div>
						<br>
						<br>
						<ol class="carousel-indicators">
						    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
						    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
						    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
						</ol>
					</div>
				</div><!-- col-lg-8 -->
			</div><!-- row -->
		</div><!-- container -->
	</div>	<!-- f -->

	<!-- ========== CONTACT SECTION ========== -->
	<section id="contact" name="contact"></section>
	<div id="f">
		<div class="container">
			<div class="row">
				<h3>CONTACT ME</h3>
				<p class="centered"><i class="icon icon-circle"></i><i class="icon icon-circle"></i><i class="icon icon-circle"></i></p>

				<div class="col-lg-6 col-lg-offset-3">
					<p>Some Avenue, 987<br/>Bangalore, India<br/>+91 1234567</p>
					<p></p>
					<p><button type="button" class="btn btn-warning">YEAH! CONTACT ME NOW!</button></p>
				</div>
			</div>
		</div>
	</div>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
	<script src="{% static 'assets/js/classie.js'%}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'assets/js/smoothscroll.js'%}"></script>
	<script src="{%static 'assets/js/main.js'%}"></script>
</body>
</html>