mini_twitter_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mtweet import urls
from django.conf.urls.static import static
from django.conf import settings
from registration.backends.simple.views import RegistrationView
import notifications.urls



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mtweet.urls')),
    url(r'^account/', include('registration.backends.simple.urls')),
    url(r'^friendship/', include('friendship.urls')),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mtweet/urls.py
from django.conf.urls import url
from mtweet import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<username>[\w\-]+)/add_profile', views.add_profile, name="add_profile"),
    url(r'^home_page', views.home_page, name='home_page'),
    url(r'^add_post', views.add_post, name='add_post'),
    url(r'^add_comment', views.add_comment, name='add_comment'),
    url(r'^show_post/(?P<pid>[\w\-]+)', views.show_post, name="show_post"),
    url(r'^like_post', views.like_post, name='like_post'),
    url(r'^show_user', views.show_user, name="show_user"),
    url(r'^profile/(?P<username>[\w\-]+)', views.profile, name='profile'),
    url(r'^add_follower', views.add_follower, name="add_follower"),
    url(r'^like_count', views.like_count, name="like_count"),
    url(r'^in_search', views.in_search, name='in_search')
]

mtweet/forms.py
from django import forms
from mtweet.models import UserProfile, Post, Comment
from django.contrib.auth.models import User

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('firstname','lastname','gender','hometown','display_picture', 'mobile')


class PostForm(forms.ModelForm):
    likes = forms.IntegerField(widget=forms.HiddenInput, initial=0)
    content = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Post
        fields = ('content', )


class CommentForm(forms.ModelForm):
    comment = forms.CharField()

    class Meta:
        model = Comment
        fields = ('comment', )

templates/homepage/home_page.html
{% extends 'homepage/hp-base.html' %}
{% load staticfiles %}

{% block title_block %}Dashboard -{{user.username}}{% endblock %}

{% block body_block %}
<style media="screen">
  body {
    overflow-x: hidden;
  }
  .box {
    border: 2px solid grey;
    color: grey;
    border-radius: 5px;
    background: #d7d7dd;
    width: 80% !important;
    height: auto;
    margin-bottom: 30px;
    margin-top: 30px;
    margin-left: 15px !important;
    text-indent: 15px;
    box-shadow: 5px 5px 2px grey;
    box-sizing: border-box;
  }
  .box-2{
    box-sizing: content-box;
    border: 2px;
    color: black;
  }
  textarea {
    width: 65%;
    border: 2px solid #B22222;
  }
  .seen {
    border: 1px solid grey;
    width: 100%;
  }
  .bttn {
    width: 50%;
    position: inherit;
  }
  .img-size{
    width: 50%;
    border-radius: 50%;
  }
  strong{
    color:black;
  }
</style>
<div class="container">
  <div class="alert alert-success" id="success-alert">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <strong>Success! </strong>
      You have Mini-Tweeted
  </div>
  <div class="container">
    <h1>hello, {{request.user.username}}</h1>
  </div>
  <!--post form-->
  <div class="container">
    <form class="form" action="/{{request.user.username}}/add_post" method="post" id='post-form'>
      {% csrf_token %}
    {% for hidden in postform.hidden_fields %}
      {{hidden}}
    {% endfor %}
      <h3>Did you Mini-Tweet today?</h3>
      <textarea cols="40" id="id_content" name="content" rows="10"></textarea>
      <hr>
      <input type="submit" value="Post" class="btn btn-success btn-lg">
    </form>
  </div>
  {{unread}}
  <!--end post form-->
  <hr>
  <hr>
  <hr>
  <!--post list-->
  <div >
  {% for post in post_list %}
        <div class="container box">
          <div class="row">
            <div class="col-sm-3">
              <img src="/media/{{ pro_profile.display_picture }}"  class="img-size" alt=""/>
            </div>
            <div class="col-sm-9">
              <h3>{{ post.user.username }}</h3>
            </div>
          </div>
          <div class="row">
            <h6>{{ post.post_time }}</h6>
          </div>
          <hr class="seen">
          <div class="row">
            <div class="container box-2">
              {{ post.content }}
            </div>
          </div>
          <hr class="seen">
          <div class="row">
            <div class="col-sm-6">
              <h6>Likes:<strong id="like-count{{post.id}}"></strong></h6>
              <button type="submit" id="like{{post.id}}" data-pid={{ post.id }} class="btn btn-xs btn-info bttn like">Like</button>
            </div>
            <div class="col-sm-6">
              <h6>Comments:<strong>{{ post.comments }}</strong></h6>
              <a href="/show_post/{{ post.id }}" class="btn btn-xs btn-danger bttn">Comment</a>
            </div>
          </div>
        </div>
  {% endfor %}
</div>
<!--end post list-->
</div>

<script>
$(function(){
  $(".like").click(function(event){
    var pid = $(event.target).attr('data-pid');
    var id = $(event.target).attr('id');
    var lk ="#"+"like-count" +pid;
    var lp ="#"+"like"+pid;
    $.ajax({
      type:'get',
      url:'/like_post',
      data:{
        'pid':pid,
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success:function(data){
        $(lk).html(data.count);
        if(data.liked)
          $(lp).css('background-color',"blue");
        else{
          $(lp).css('background-color',"#69dbf7");
        }
      },
    });
    });
  });


$(function(){
  $('#success-alert').hide();//hiding the success alert at loading of page
  $('.like').each(function(event){
    var pid = $(this).attr('data-pid');
    var lk = '#'+'like-count'+pid;
    var lp ="#"+"like"+pid;
    $.ajax({
      type:'get',
      url:'/like_count',
      data:{
        'pid':pid,
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success:function(data){
        $(lk).html(data.count);
        if(data.liked_this){
          $(lp).css("background-color","blue");
        }
        }
    });
  });
});

$(document).on('submit','#post-form', function(e){
  e.preventDefault();
  $.ajax({
    type:'post',
    url:'/add_post',
    data:{
      'content':$('#id_content').val(),
      csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
    },
    success:function(data){
        $('#id_content').val('');
        $("#success-alert").alert();
        $("#success-alert").fadeTo(2000, 500).slideUp(500, function(){
          $("#success-alert").slideUp(500);
        });   
    },
  });
});


</script>


{% endblock %}

templates/homepage/profile.html
{% extends 'homepage/hp-base.html' %}
{% load staticfiles %}
{% load friendshiptags %}

{% block title_block %}Profile- {{pro_user.username}}{% endblock %}

{% block body_block %}
<style media="screen">
  .img-size {
    width: 25%;
    border-radius: 50%;
  }
  .bttn{
    background: white;
    border: 2px;
    border-color: #0074D9;
    border-style: solid;
    border-radius: 7px !important;
    color: #0074D9;
  }
  .bttn:hover{
    box-shadow: 2px 2px 2px #0074D9 inset;
    color: #0074D9;
  }
  .box {
    border: 2px solid grey;
    color: grey;
    border-radius: 5px;
    background: #d7d7dd;
    width: 80% !important;
    height: auto;
    margin-bottom: 30px;
    margin-top: 30px;
    margin-left: 15px !important;
    text-indent: 15px;
    box-shadow: 5px 5px 2px grey;
    box-sizing: border-box;
  }
  .box-2{
    box-sizing: content-box;
    border: 2px;
    color: black;
  }
  .bttn2 {
    width: 50%;
    position: inherit;
  }
</style>

  <div class="container">
    <div class="row">
      <img src="{{MEDIA_URL}}{{pro_profile.display_picture}}" alt="{{pro_user.username}}'s display picture" class="img-size img-thumbnail">
    </div>
    <div class="container">
      <h1>{{ pro_profile.firstname }} {{ pro_profile.lastname }}</h1>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
            <h3>Hometown:</h3>
        </div>
        <div class="col-sm-6">
          <h3>{{ pro_profile.hometown }}</h3>
        </div>
      </div>

    <div class="row">
      <div class="col-sm-6">
          <h3>Mobile:</h3>
      </div>
      <div class="col-sm-6">
        <h3>{{ pro_profile.mobile }}</h3>
      </div>
    </div>
  </div>
<hr><hr>
{% ifnotequal user pro_user%}
  <button type="button" name="button" class="btn bttn btn-lg" id="follow" data-username="{{pro_user.username}}">follow</button>
{% endifnotequal %}
<hr>
<hr>
{% ifequal user pro_user %}
  <div class="conatiner">
    <div class="row">
      <div class="col-md-6">
        <button type="button" name="button" id="following" class="btn btn-sm btn-alert">Following</button>
        <div id="fol">
          <p>{% following user %}</p>
        </div>
      </div>
      <div class="col-smd-6">
        <button type="button" name="button" id="follower" class="btn btn-sm btn-alert">Followers</button>
        <div id="flwr">
          <p>{% followers request.user %}</p>
        </div>
      </div>
    </div>
  </div>
  {% endifequal %}
  <div class="container">
    {% ifequal user pro_user %}
      <div>
        {% for post in post_list_user %}
        <div class="container box">
          <div class="row">
            <div class="col-sm-3">
              <img src="/media/{{ profile.display_picture }}"  class="img-size" alt=""/>
            </div>
            <div class="col-sm-9">
              <h3>{{ post.user.username }}</h3>
            </div>
          </div>
          <div class="row">
            <h6>{{ post.post_time }}</h6>
          </div>
          <hr class="seen">
          <div class="row">
            <div class="container box-2">
              {{ post.content }}
            </div>
          </div>
          <hr class="seen">
          <div class="row">
            <div class="col-sm-6">
              <h6>Likes:<strong id="like-count{{post.id}}"></strong></h6>
              <button type="submit" id="like{{post.id}}" data-pid={{ post.id }} class="btn btn-xs btn-info  bttn2">Like</button>
            </div>
            <div class="col-sm-6">
              <h6>Comments:<strong>{{ post.comments }}</strong></h6>
              <a href="/show_post/{{ post.id }}" class="btn btn-xs btn-danger bttn2">Comment</a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    {% else %}
    <div>
      {% for post in post_list_pro %}
        <div class="container box">
          <div class="row">
            <div class="col-sm-3">
              <img src="/media/{{ pro_profile.display_picture }}"  class="img-size" alt=""/>
            </div>
            <div class="col-sm-9">
              <h3>{{ post.user.username }}</h3>
            </div>
          </div>
          <div class="row">
            <h6>{{ post.post_time }}</h6>
          </div>
          <hr class="seen">
          <div class="row">
            <div class="container box-2">
              {{ post.content }}
            </div>
          </div>
          <hr class="seen">
          <div class="row">
            <div class="col-sm-6">
              <h6>Likes:<strong id="like-count{{post.id}}"></strong></h6>
              <button type="submit" id="like{{post.id}}" data-pid={{ post.id }} class="btn btn-xs btn-info like bttn2">Like</button>
            </div>
            <div class="col-sm-6">
              <h6>Comments:<strong>{{ post.comments }}</strong></h6>
              <a href="/show_post/{{ post.id }}" class="btn btn-xs btn-danger bttn2 ">Comment</a>
            </div>
          </div>
        </div>
  {% endfor %}
    </div>
  {% endifequal %}
  </div>

</div>

<script>
  $(function(){
    $('#follow').click(function(){
      var username = $('#follow').attr('data-username');
      $.get('/add_follower', {'username':username}, function(){
        alert('followed');
      });
  });
});
$(function(){
  $('#fol').hide();
  $("#following").click(function(){
    $('#fol').toggle();
  });
});
$(function(){
  $('#flwr').hide();
  $("#follower").click(function(){
    $('#flwr').toggle();
  });
});
$(function(){
  $(".like").click(function(event){
    var pid = $(event.target).attr('data-pid');
    var id = $(event.target).attr('id');
    var lk ="#"+"like-count" +pid;
    var lp ="#"+"like"+pid;
    $.ajax({
      type:'get',
      url:'/like_post',
      data:{
        'pid':pid,
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success:function(data){
        $(lk).html(data.count);
        if(data.liked)
          $(lp).css('background-color',"blue");
        else{
          $(lp).css('background-color',"#69dbf7");
        }
      },
    });
    });
  });


$(function(){
  $('#success-alert').hide();//hiding the success alert at loading of page
  $('.like').each(function(event){
    var pid = $(this).attr('data-pid');
    var lk = '#'+'like-count'+pid;
    var lp ="#"+"like"+pid;
    $.ajax({
      type:'get',
      url:'/like_count',
      data:{
        'pid':pid,
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success:function(data){
        $(lk).html(data.count);
        if(data.liked_this){
          $(lp).css("background-color","blue");
        }
        }
    });
  });
});
</script>

{% endblock %}

templates/homepage/show_post.html
{%extends 'mtweet/base.html'%}
{% load staticfiles %}

{% block title_block %}{{ post.user }}{% endblock %}
{% block body_block %}
<style media="screen">
  input[type='text']{
    width: 50%;
  }
  li {
    color: black;
  }
</style>


<div class="conatainer">
  <div class="container">
    <div class="row">
      <h2>{{ post.user.username}}</h2>
    </div>
    <div class="row">
      <h5>{{ post.post_time}}</h5>
    </div>
    <hr>
    <div class="row" style="color:black">
      <p>{{ post.content }}</p>
    </div>
  </div>
<hr>
  <div class="container">
    <form id=comment-form action="/add_comment" method="post">
      {% csrf_token %}
      {{ comment_form }}
      <input type="hidden" name="pid" value="{{post.id}}", id="pid">
      <input type="submit"  value="Comment">
    </form>
  </div>

  <div class="container">
    <h1>Comments</h1>
    <ul id="show_comm">

    </ul>
    {% if not comment_list %}
    <li>No comments. Be the first one!</li>
    {% else %}
    {% for comment in comment_list %}
    <ul>
      <li><strong>{{comment.poster}}</strong> says: {{comment.comment}}</li>
    </ul>
    {% endfor %}
    {% endif %}
  </div>
</div>

  <script>
  $(document).on('submit', '#comment-form', function(e){
    e.preventDefault();
    $.ajax({
      type:"POST",
      url:'/add_comment',
      data:{
      comment:$("#id_comment").val(),
      pid:$("#pid").val(),
      csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success:function(data){
          $('#id_comment').val('');
          $("#show_comm").append('<li><strong>' + data.user + "</strong> says: " + data.comment + '</li>');
      },
    });
  });

  </script>

{% endblock %}

templates/homepage/show_user.html
{% extends 'homepage/hp-base.html' %}
{% load staticfiles %}
{% load notifications_tags %}

{% block title_block %}User List{% endblock %}

{% block body_block %}
<hr>
<style type="text/css">
	.box{
		border: 2px !important;
		background: #d5ddea;
		width: 150px;
    color: red;
	}
  input{
    border-radius: 3px;
    box-shadow: 2px 2px grey;
    border-color: #4adcf9;
  }
</style>

  <div class="container">
  <div class="container ">
  	<input type="text" name="search" id="suggestions" placeholder="Search here...">
  	<div class="box">
  		<ul id="users"></ul>
  	</div>
  </div>
  {% notifications_unread %}
  {% live_notify_badge %}
  {% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}
  {% live_notify_list classes="dropdown-menu" %}
    {% for users in user_list %}
      {% ifnotequal user.username users.username %}
      <div class="container">
        <h2><a href="{% url 'profile' users.username %}">{{ users.username }}</a></h2>
      </div>
      {% endifnotequal %}
    {% endfor %}
  </div>

  <script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>

  <script type="text/javascript">
  	$(function(){
  		$('#suggestions').keyup(function(){
  			$('#users').empty();
  			var search = $('#suggestions').val();
  			$.ajax({
  				type: 'get',
  				url: '/in_search',
  				data:{
  					'search':search,
  					csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
  				},
  				success:function(data){
  					$.each(data, function(index, element){
  						$('#users').append('<li><a href="/profile/'+element.fields.username+'">'+element.fields.username+'</a></li>');
  					})
  				},
  			});
  		});
  	});
  </script>
{% endblock %}